name: MyNebo CI/CD Pipeline
on:
  push:
    branches:
      - 'master'
      - 'stage'
  pull_request:
    branches:
      - 'master'
      - 'stage'

jobs:
  # Run code tests before building the image, to ensure it is good to go
  build-push:
    name: Run code tests
    runs-on: ubuntu-latest

  steps:
    - name: Checkout app code
    - uses: actions/checkout@v2
