name: MyNebo CI/CD Pipeline
on:
  push:
    branches:
      - 'master'
      - 'stage'
  pull_request:
    branches:
      - 'master'
      - 'stage'

  release:
    types: [published, edited]

jobs:
  # Run code tests before building the image, to ensure it is good to go
  build:
    name: Run code tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout app code
    - uses: actions/checkout@v2

    - name: Setup python
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

